version = 3.11.0

align.preset = most
includeCurlyBraceInSelectChains = false
maxColumn = 120
project.git = true
rewrite {
  rules = [SortImports, RedundantBraces, RedundantParens, PreferCurlyFors]
  redundantBraces.generalExpressions = false
}
runner.dialect = scala3
spaces.beforeContextBoundColon = Always

fileOverride {
  "glob:**/project/*.scala" {
    runner.dialect = scala212source3
  }
  "glob:**/*.sbt" {
    runner.dialect = scala212source3
  }
}
