addSbtPlugin("org.http4s"    % "sbt-http4s-grpc" % "0.3.0")
addSbtPlugin("com.thesamet"  % "sbt-protoc"      % "1.0.8")
addSbtPlugin("org.scalameta" % "sbt-scalafmt"    % "2.6.0")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix"    % "0.14.6")
addSbtPlugin("org.typelevel" % "sbt-tpolecat"    % "0.5.3")
